version: 1
update_configs:
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    default_reviewers: ["imbsky"]
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers: ["imbsky"]
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
