name: Main workflow

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    if: github.repository == 'imbsky/coq-to-ocaml-to-js'

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      node-version: 13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1.4.0
        with:
          node-version: ${{ env.node-version }}

      - name: Restore esy cache
        uses: actions/cache@v1.1.2
        id: esy
        with:
          path: ~/.esy
          # prettier-ignore
          key: ${{ runner.os }}-esy-${{ hashFiles(format('{0}{1}', github.workspace, '/esy.lock/index.json')) }}
          restore-keys: |
            ${{ runner.os }}-esy-

      - name: Get yarn cache directory
        id: yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ steps.yarn.outputs.dir }}
          # prettier-ignore
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install esy
        run: npm install --global esy

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Install and build opam packages
        run: esy

      - name: Extract Coq to OCaml, and compile OCaml to JavaScript
        run: make build
